PrimeFaces.locales['pt'] = {  
                    closeText: 'Fechar',  
                    prevText: 'Anterior',  
                    nextText: 'Proximo',  
                    currentText: 'HOJE',  
                    monthNames: ['Janeiro', 'Fevereiro', 'Marco', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],  
                    monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],  
                    dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],  
                    dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],  
                    dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],  
                    weekHeader: 'Semana',  
                    firstDay: 0,  
                    isRTL: false,  
                    showMonthAfterYear: false,  
                    yearSuffix: '',  
                    timeOnlyTitle: 'So Horas',  
                    timeText: 'Tempo',  
                    hourText: 'Hora',  
                    minuteText: 'Minuto',  
                    secondText: 'Segundo',  
                    ampm: false,  
                    month: 'MÊS',  
                    week: 'S',  
                    day: 'D',  
                    allDayText: 'Todo o Dia'  
                };  
